name: Deploy Aha Clone App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Deploy to Azure VM via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.VM_SSH_KEY }}
          script: |
            echo "Connected to VM"

            # Clone if not exists, else go inside
            cd ~/aha-clone || git clone https://github.com/rayudumanichand/aha-clone.git && cd aha-clone

            # Pull latest changes
            git pull origin main

            # Install dependencies
            npm ci

            # Build project
            npm run build

            # Clear old files
            sudo rm -rf /var/www/html/*

            # Copy build to nginx folder
            sudo cp -r build/* /var/www/html/

            # Restart nginx
            sudo systemctl restart nginx

            echo "Deployment Successful"
